import type { Metadata } from "next";
import { Montserrat, Nunito, Salsa } from "next/font/google";
import "./globals.css";


const montserrat = Montserrat({ subsets: ["latin"], style: ["italic", "normal"], weight: ["400"]});
const nunito = Nunito({ subsets: ["latin"], weight: ["400", "700"] });
const salsa = Salsa({ subsets: ["latin"], weight: ["400"] });


  



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>{children}</body>
    </html>
  );
}
