import type { Metadata } from "next";
import { Montserrat, Nunito, Salsa } from "next/font/google";
import "./globals.css";


const montserrat = Montserrat({ subsets: ["latin", "cyrillic"], style: ["italic", "normal"]});
const nunito = Nunito({ subsets: ["latin"], display: 'swap', style:"normal", variable: '--nunito' });
const salsa = Salsa({ subsets: ["latin"], weight: ["400"], variable: '--salsa' });


  



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${salsa} ${nunito}`}>{children}</body>
    </html>
  );
}
